apiVersion: apps/v1
kind: Deployment
metadata:
  name: coink-backend
  labels:
    app: coink-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coink-backend
  template:
    metadata:
      labels:
        app: coink-backend
    spec:
      containers:
      - name: coink-backend
        image: 127263143822.dkr.ecr.us-east-2.amazonaws.com/coink-back:#{SHA}#
        ports:
        - name: http
          containerPort: 3000
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 300m
        env:
          - name: USER_DB
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: username
          - name: PASS_DB
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password              
---
apiVersion: v1
kind: Service
metadata:
  name: coink-backend
spec:
  type: NodePort
  selector:
    app: coink-backend
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 30008