version: '3'
services:
  front:
    container_name: coink-front
    image: front/coink
    build:
      context: .
    ports:
      - "80:80"
    networks:
      - net
  back:
    container_name: coink-back
    image: back/coink
    build:
      context: backend/
    ports:
      - "3000:3000"
    networks:
      - net

networks:
  net: