apiVersion: apps/v1
kind: Deployment
metadata:
  name: coink-frontend
  labels:
    app: coink-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coink-frontend
  template:
    metadata:
      labels:
        app: coink-frontend
    spec:
      containers:
      - name: coink-frontend
        image: 127263143822.dkr.ecr.us-east-2.amazonaws.com/coink-front:#{SHA}#
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 300m
---
apiVersion: v1
kind: Service
metadata:
  name: coink-frontend
spec:
  type: NodePort
  selector:
    app: coink-frontend
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30007